apiVersion: v1
kind: Service
metadata:
  name: database
  labels:
    app.kubernetes.io/name: database
    app.kubernetes.io/component: database
    app.kubernetes.io/part-of: foxtown
spec:
  selector:
    app.kubernetes.io/name: database
    app.kubernetes.io/component: database
  ports:
    - port: 3306
      targetPort: 3306
      protocol: TCP
  type: ClusterIP
